---
name: Geo-Proj-GoogleMaps
version: 0.0.1
author:
  - 'OHTSUKA Ko-hei <nene@kokogiko.net>'
abstract: Add Google Maps projection to Geo::Proj
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Geo::Proj: 0.06
  version: 0
build_requires:
  Test::Base: 0
provides:
  Geo::Proj::GoogleMaps:
    file: lib/Geo/Proj/GoogleMaps.pm
    version: 0.0.1
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
